// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('asignacionCorrecta', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('asignacionCorrecta', async function() {
    await driver.get("http://localhost:3000/asignacion")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[2]/select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(6) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Lenguaje']")).click()
    }
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/button")).click()
    await driver.findElement(By.xpath("(//button[@type=\'button\'])[3]")).click()
    await driver.close()
  })
})
