// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('inicioSesionCorrecto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('inicioSesionCorrecto', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1050, height: 708 })
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label/input")).sendKeys("wiliamborrayo@gmail.com")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[2]/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[2]/input")).sendKeys("1234")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/button")).click()
    await driver.findElement(By.xpath("(//button[@type=\'button\'])[3]")).click()
    await driver.close()
  })
})
