// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('registroIncorrecto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('registroIncorrecto', async function() {
    await driver.get("http://localhost:3000/registro")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label/input")).sendKeys("william")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[2]/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[2]/input")).sendKeys("borrayo")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[5]/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[5]/input")).sendKeys("1234")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[6]/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[6]/input")).sendKeys("1234")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/button")).click()
    await driver.findElement(By.xpath("(//button[@type=\'button\'])[3]")).click()
    await driver.close()
  })
})
