// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('registro', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('registro', async function() {
    await driver.get("http://localhost:3000/registro")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label/input")).sendKeys("william")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[2]/input")).sendKeys("borrayo")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[3]/input")).sendKeys("correo")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[4]/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[4]/input")).sendKeys("2022-06-21")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[5]/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[5]/input")).sendKeys("1234")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[6]/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/label[6]/input")).sendKeys("1234")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/form/button")).click()
    assert(await driver.switchTo().alert().getText() == "registrado")
    await driver.close()
  })
})
